#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require ('./vendor/autoload.php');

require('./src/FizzBuzz/fizzbuzz.php');
require('./tests/FizzBuzz/test.php');

use FizzBuzz\App2;

$fizzbuzz = new App2();
$fizzbuzz->stepTwo(30);
